### ISSUE TITLE
Replace core file fields

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/reference#18]
Since files are actually entities should we use same universal field type for files and provide upgrade path from file fields?

#1 is very similar I guess. I'm going to mark this one as _question_, because it is needed to be discussed first.

**Comment by mikemccaffrey** [comment]
I think it is safe to say that we are not going to do this. The Reference module is intended to be a simple, general purpose way to link different entities together, but it is not intended to solve every single type of entity relationship.

In this case, the file module has some fairly complicated logic that keeps track of which files are being referenced by which entities so that orphaned files can be removed, and if we change how that works too much, it will be breaking backwards compatibility.

However, thanks for the question, @Al-Rozhkov!
