### ISSUE TITLE
Hooks so that we can have modules like Node Reference URL Widget, Reference Prepopulate, (Node) Reference Dialog

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/reference#19]
Entity Reference has hooks so that other modules can modify the behaviour of the field in various situations. It would be good to have the hooks in place before it goes into core so there's a good foundation.

**Comment by olafgrabienski** [comment]
Related: [UX - Provide links to add and edit references through a dialog](https://github.com/backdrop-contrib/reference/issues/12)

**Comment by mikemccaffrey** [comment]
> @herbdool: Entity Reference has hooks so that other modules can modify the behaviour of the field in various situations. It would be good to have the hooks in place before it goes into core so there's a good foundation.

Any idea on what hooks need to be added? It would be great to know exactly how such hooks will be used, and some examples from existing reference-related modules. We can always add more hooks to core, but can't really remove them when they are there.

I'm imagining that most customizations will be implemented through contrib modules defining their own widgets and formatters that can be selected for use with a reference field, rather than messing with the default widget and formatter.

**Comment by mikemccaffrey** [comment]
Unfortunately, we can't have a single issue and single solution to provide all possible hooks for all possible contrib integrations. Can folks please submit separate issues for each individual hook that is desired along with info on how it will be used?
