### ISSUE TITLE
I am interested in becoming a co-maintainer on reference module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/reference#52]
I am interested in becoming a co-maintainer on reference module so that I can help work out some of the kinks, and get an initial release out. 

I promise not to merge any PRs with upgrade paths until enough people have tested the upgrades, and agree on the approach :)

PR: https://github.com/backdrop-contrib/reference/pull/53

**Comment by klonos** [comment]
Thanks for applying to take over @jenlampton 🙏 

Since there is no current maintainer listed in the README of that project, plus also given that you have opened this issue here a couple of weeks ago, and also the fact that you are keeping the last known person to have worked on that module as a co-maintainer, I'm confident to merge that PR 👍

**Comment by mikemccaffrey** [comment]
@jenlampton Have at it!

**Comment by jenlampton** [comment]
Thank you!
