### ISSUE TITLE
ReferenceFieldTestCase return exceptions on autocomplete test

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/reference#9]
Tests are throwing many exceptions not allowing them to complete.

**Comment by serundeputy** [comment]
This `PR`: https://github.com/backdrop-contrib/reference/pull/10  allows the test suite for reference to run.

```
geoff@gspmbp backdrop (1.x) $ sudo -u _www core/scripts/run-tests.sh --url="http://backdrop" ReferenceFieldTestCase --color --verbose

Backdrop test run
---------------

Tests to be run:
 - Reference field test (ReferenceFieldTestCase)

Test run started:
 Thursday, November 10, 2016 - 8:00pm

Test summary
------------

Reference: Reference field test (ReferenceFieldTestCase) 22 passes, 0 fails, 0 exceptions, and 7 debug messages

Test run duration: 5 sec

Detailed test results
---------------------
```

**Comment by serundeputy** [comment]
@mikemccaffrey @quicksketch this is a ping;

**Comment by mikemccaffrey** [comment]
Hey @serundeputy, sorry but I merged your pull request, but then wrote overtop of it. I'm trying to figure out a better way to handle the function that was returning the exceptions.

**Comment by mikemccaffrey** [comment]
Hey @serundeputy, I believe that you were encountering all the exceptions since the test case that I had committed was passing the wrong arguments to the autocomplete callback, and the autocomplete callback wasn't smart enough to handle that. 

I just added a conditional to make sure that the field name, entity name, and bundle are all valid, and to return access denied if they are not. (7755871)

I also rewrote that test to explicitly test that case of bad arguments being passed in. (4567a09)

I'm closing this issue for now, but please let me know if you have any problems around this issue.

**Comment by serundeputy** [comment]
no problem thanks @mikemccaffrey .  Do you think it is stable enough to start building out the functional tests now?

thanks,
~Geoff
